# Generated by Django 6.1.1 on 2026-09-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('gateway', models.CharField(max_length=50, verbose_name='درگاه')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='شناسه درگاه')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='کد پیگیری')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='شناسه تراکنش داخلی')),
                ('callback_url', models.URLField(blank=True, verbose_name='آدرس بازگشت')),
                ('payment_url', models.URLField(blank=True, verbose_name='آدرس پرداخت')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ درگاه')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_288dd3_idx'), models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('authority', ''), _negated=True), fields=('authority',), name='unique_payment_authority'), models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('order',), name='unique_successful_payment_per_order')],
            },
        ),
    ]
