# Generated by Django 6.1.1 on 2026-09-20 09:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('code_hash', models.CharField(max_length=64, verbose_name='هش کد')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cها')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف',
                'verbose_name_plural': 'کدهای یکبارمصرف',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[accounts.models.validate_iranian_mobile], verbose_name='شماره موبایل'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['phone_number', 'is_used'], name='accounts_ph_phone_n_f9d2ef_idx'),
        ),
    ]
