# Generated by Django 6.1.1 on 2026-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneotp_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_phone_n_613c4a_idx',
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='تاریخ انقضا'),
        ),
    ]
