# Generated by Django 6.1.1 on 2026-09-24 09:41

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_expires_at_and_more'),
        ('products', '0004_remove_productimage_products_pr_product_1b7905_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_user_created_idx',
            old_name='orders_orde_user_id_0ae59f_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_status_created_idx',
            old_name='orders_orde_status_079368_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_payment_expiry_idx',
            old_name='orders_orde_status_db7b4d_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین تغییر وضعیت'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=12, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قیمت کل'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orderitem_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orderitem_product_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku'], name='orderitem_sku_idx'),
        ),
    ]
