# Generated by Django 6.1.1 on 2026-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productattribute_productimage_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('id',), 'verbose_name': 'تنوع محصول', 'verbose_name_plural': 'تنوع\u200cهای محصول'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=80, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=80, unique=True, verbose_name='کد تنوع'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'slug'], name='products_br_is_acti_8e768b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'slug'], name='products_ca_is_acti_83e9a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_attribute_name_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_variant_name_per_product'),
        ),
    ]
