# Generated by Django 6.1.1 on 2026-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_options_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productimage',
            name='products_pr_product_1b7905_idx',
        ),
        migrations.RenameIndex(
            model_name='brand',
            new_name='brand_active_slug_idx',
            old_name='products_br_is_acti_8e768b_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='category_active_slug_idx',
            old_name='products_ca_is_acti_83e9a4_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_available_category_idx',
            old_name='products_pr_is_avai_078cf7_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_available_brand_idx',
            old_name='products_pr_is_avai_d0ff9a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_featured_available_idx',
            old_name='products_pr_is_feat_ce1607_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_created_idx',
            old_name='products_pr_created_bce1a7_idx',
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='قابل فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محصول ویژه'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'sort_order'], name='product_image_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
    ]
